### ISSUE TITLE
request: adding context modifiers

### ISSUE THREAD

**Issue by raphaelgoetter** [tokencss/tokencss#12]
Hello,

I am just discovering this tool and I have high hopes for these CSS Tokens, bravo!

Are there any "class modifiers" like Tailwind for example?  I'm thinking of the equivalents of `md:text-hotpink` or `dark:text-hotpink`.

And if yes, how do you see the addition of these features?

In the same way, how to manage Media Queries (which don't work with "simple CSS variables"?)

```css
@media (min-width: screen-lg) {
  /* does not work if `screen-lg` is replaced by a CSS variable */
}
```

Thanks in advance for your help!

**Comment by meduzen** [comment]
> In the same way, how to manage Media Queries (which don't work with "simple CSS variables"?)
> 
> ```css
> @media (min-width: screen-lg) {
>   /* does not work if `screen-lg` is replaced by a CSS variable */
> }
> ```

Maybe Custom Media Queries are an answer. I wrote a [quick explainer](https://github.com/meduzen/--media.scss/blob/main/docs/custom-media-queries.md#declaration) for them in the context of a SCSS package I maintain.

**Comment by lukeshafer** [comment]
> In the same way, how to manage Media Queries (which don't work with "simple CSS variables"?)
> 
> ```css
> @media (min-width: screen-lg) {
>   /* does not work if `screen-lg` is replaced by a CSS variable */
> }
> ```

@natemoo-re helped me with this on [Twitter yesterday](https://twitter.com/lksh_dev/status/1571988599121367040?s=20&t=vAyrReARxoHP5xtYPNaVZw), so I have two notes:

1. Media queries aren't working now but will be fixed soon
2. `@media (min-width: screen-lg)` isn't the right syntax -- you just want `@media lg` (but this still won't work until it's fixed)

I would guess @meduzen is right and it uses custom media queries, because you can just replace the `lg` keyword with `(--query-name)` and it would work, just like the rest of the replacements use custom properties

**Comment by lukeshafer** [comment]
As far as the modifiers, I have found I could get kinda close to the tailwind ways with postcss through the [postcss-nesting](https://www.npmjs.com/package/postcss-nesting) and [postcss-darkmode](https://www.npmjs.com/package/postcss-darkmode) packages (though the latter is only needed if you want class-based dark mode). 

Then in my `tokens.config.json` I added 

```json
"media": {
  "darkmode": { "value": "(prefers-color-scheme: dark)" }
},
```

Which would (theoretically) allow me to do something like 

```css
h1 {
  color: blue.0;
  @media dark {
    color: blue.9;
  }
  &:hover {
    color: red.0
    @media dark {
        color: red.9
    }
  }
}
```

And you could slot in any other pseudo-selector or media query! Of course, until media queries are fixed you'll have to write out the query or use a Custom Media Query with postcss.

ALL that said, I think modifiers would be pretty cool!! Though I'm unsure what syntax would be best - something like

```css
p {
  /* this? */
  color: blue;
  md.color: red; /* overwriting properties themselves */

  /* or this? */
  color: blue;
  color: md.red; /* highjacking the way css overwrites values */

  /* or something else? */
}
```
