### ISSUE TITLE
Some design-tokens are not getting processed correctly

### ISSUE THREAD

**Issue by shaal** [tokencss/tokencss#2]
See the following code and screenshot. 

`packages/playground/src/main.css`
```
.boxes {
    display: flex;
    gap: sm;
    margin-top: 4xl;
}

.box {
    --size: 6xl;
    --bg: red.6;
    width: var(--size);
    height: var(--size);
    background: var(--bg);
    box-shadow: xl;

    &:first-child {
        --bg: blue.6;
    }

    &:last-child {
        --bg: green.6;
    }
}
```
![image](https://user-images.githubusercontent.com/22901/170631106-06d32a35-03c3-4a48-bbfd-fa9eb8bc5336.png)

Inspecting that page with the browser -
 `.boxes` was processed correctly
```css
.boxes {
    display: flex;
    gap: var(--space-sm);
    margin-top: var(--space-4xl);
```

But `.box` was processed incorrectly.
`6xl`, `red.6`, `xl` did not convert to the correct value.
```css
.box {
    --size: 6xl;
    --bg: red.6;
    width: var(--size);
    height: var(--size);
    background: var(--bg);
    box-shadow: xl;
}
```

Steps to replicate:
1. `cd packages/playground`
1. `yarn install`
1. `yarn dev`
