### ISSUE TITLE
Simple references and math?

### ISSUE THREAD

**Issue by djmtype** [tokencss/tokencss#22]
I assume all values need to be flattened first? 

Tried and failed: `Cannot read properties of undefined (reading '$path')`

```json
"space": {
    "scale": {
      "value": "1.333"
    },
    "xs": {
      "value": ".5rem"
    },
    "sm": {
      "value": "{space.xs} * {space.scale}"
    },
    "md": {
      "value": "{space.sm} * {space.scale}"
    },
    "lg": {
      "value": "{space.md} * {space.scale}"
    },
    "xl": {
      "value": "{space.lg} * {space.scale}"
    }
  },
```

Using the above example would be extremely useful when managing a design system, like when using Figma Tokens. Typically, I set up a value that represents a ratio for spacing and font sizes. 

Prior to TokenCSS, I'd use [Token Transformer](https://www.npmjs.com/package/token-transformer) to flatten the values from Figma Tokens, then use Style Dictionary to create css custom properties.

Otherwise, without TokenCSS or Style Dictionary, I'd write out my custom properties like so: 
```css
:root {
  --space-scale: 1.333;
  --space-xs: 0.5rem;
  --space-sm: calc(var(--space-xs) * var(--space-scale));
}
```
