### ISSUE TITLE
Add support for a "theme" function inside

### ISSUE THREAD

**Issue by ericfennis** [tokencss/tokencss#24]
To use design tokens inside `calc` functions would be nice to able to use a function to select tokens for advanced use cases.

For example:
```css
.my-div {
  width: calc(theme(space.sm) * 2)
}
```
